# Generated by Django 5.2 on 2025-12-08 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        upload_to="pass_photo/%Y/%m/%d/", verbose_name="Фото на пропуск"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NotUnVerify", "Не проверен"),
                            ("Verify", "Проверен"),
                            ("Printed", "Нейтрально"),
                        ],
                        default="received",
                        verbose_name="статус",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
