# Generated by Django 5.2.9 on 2025-12-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pass',
            name='status',
            field=models.CharField(choices=[('NotVerify', 'Не проверен'), ('Verify', 'Проверен'), ('Printed', 'Нейтрально')], default='NotUnVerify', verbose_name='статус'),
        ),
    ]
