# Generated by Django 5.2.9 on 2025-12-18 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("passes", "0002_alter_pass_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pass",
            name="photo",
        ),
        migrations.AlterField(
            model_name="pass",
            name="status",
            field=models.CharField(
                choices=[
                    ("NotFilledIn", "Не заполнено"),
                    ("NotVerify", "Не проверен"),
                    ("Verify", "Проверен"),
                    ("Printed", "Нейтрально"),
                ],
                default="NotFilledIn",
                verbose_name="статус",
            ),
        ),
        migrations.AlterField(
            model_name="pass",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_pass",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
