# Generated by Django 5.2.9 on 2025-12-18 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("passes", "0002_alter_pass_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pass",
            name="photo",
        ),
    ]
