# Generated by Django 5.2 on 2025-12-19 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("passes", "0003_remove_pass_photo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="pass",
            name="status",
            field=models.CharField(
                choices=[
                    ("NotFilledIn", "Не заполнено"),
                    ("NotVerify", "Не проверен"),
                    ("Verify", "Проверен"),
                    ("Printed", "Нейтрально"),
                ],
                default="NotFilledIn",
                verbose_name="статус",
            ),
        ),
        migrations.AlterField(
            model_name="pass",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_pass",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
