# Generated by Django 5.2.9 on 2025-12-13 11:41

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.user",),
            managers=[
                ("objects", users.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=50)),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="avatars/",
                        verbose_name="Аватар",
                    ),
                ),
                ("middle_name", models.CharField(max_length=50)),
                (
                    "attempts_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="ошибочных попыток входа"
                    ),
                ),
                (
                    "attempts_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="время блокировки"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Связь с пользователем",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ученик",
                    ),
                ),
            ],
        ),
    ]
