# Generated by Django 5.2.9 on 2025-12-04 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileStudent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("middle_name", models.CharField(max_length=50)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Фото пользователя",
                        null=True,
                        upload_to="photos/",
                        verbose_name="фото",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Связь с пользователем",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ученик",
                    ),
                ),
            ],
        ),
    ]
