# Generated by Django 5.2.9 on 2025-12-17 17:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        verbose_name="название учебного заведения",
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="краткое название"
                    ),
                ),
                (
                    "information",
                    models.TextField(
                        validators=[
                            django.core.validators.MaxLengthValidator(limit_value=5000)
                        ],
                        verbose_name="описание",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="institutions/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["png", "jpg", "svg"],
                                message="Недопустимый формат изображения",
                            )
                        ],
                        verbose_name="логотип учебного заведения",
                    ),
                ),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_institutions",
                        to="users.user",
                        verbose_name="администратор организации",
                    ),
                ),
            ],
            options={
                "verbose_name": "учебное заведение",
                "verbose_name_plural": "учебные заведения",
            },
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="название группы"),
                ),
                (
                    "course",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, "Курс обучения не может быть меньше 1"
                            ),
                            django.core.validators.MaxValueValidator(
                                6, "Курс не может быть больше 6"
                            ),
                        ],
                        verbose_name="курс",
                    ),
                ),
                (
                    "year",
                    models.DateField(default=2025, verbose_name="год поступления"),
                ),
                (
                    "curator",
                    models.ForeignKey(
                        limit_choices_to={"role": "curator"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curated_groups",
                        to="users.user",
                        verbose_name="куратор",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups",
                        to="organizations.institution",
                        verbose_name="учебное заведение",
                    ),
                ),
            ],
            options={
                "verbose_name": "группа",
                "verbose_name_plural": "группы",
            },
        ),
    ]
