# Generated by Django 5.2.9 on 2025-12-17 20:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="year",
            field=models.DateField(
                default=datetime.date(2025, 1, 1), verbose_name="год поступления"
            ),
        ),
    ]
