# Generated by Django 5.2.9 on 2025-12-17 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_alter_group_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="institution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="groups",
                to="organizations.institution",
                verbose_name="учебное заведение",
            ),
        ),
    ]
